name: "semver-tag-creator-action"
description: "Creates a new tag using semantic versioning format ([MAJOR].[MINOR].[PATCH]). Increments the minor number. Major is passed in. Patch is always 1."
inputs:
  major-version:
    description: "Major version number to use when looking for/creating tags."
    required: true
    default: 1
outputs:
  version:
    description: "The new tag version number"
runs:
  using: "node24"
  main: "./dist/index.js"
