name: 'semver-tag-creator-action'
description: 'Creates a new tag using semantic versioning format ([MAJOR].[MINOR].[PATCH]). We only increment the minor number. Major needs to be passed in. Patch is always 0.'
inputs:
  major-version:
    description: 'Major version number to use when looking for/creating tags.'
    required: true
    default: 1
outputs:
  version:
    description: 'The new tag version number'
runs:
  using: 'node12'
  main: './lib/main.js'